libmseed compilation: only works on my machine with this change
which is weird because the error I get without this change is the
following which that "-std=c99" seems to be there for in the first
place?

fileutils.c: In function ‘ms3_mstl_init_fd’:
fileutils.c:91:24: warning: implicit declaration of function ‘fdopen’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
   91 |   msfp->input.handle = fdopen (fd, "rb");
      |                        ^~~~~~
      |                        fopen
fileutils.c:91:22: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   91 |   msfp->input.handle = fdopen (fd, "rb");
      |                      ^
msio.c: In function ‘msio_fopen’:
msio.c:195:8: warning: implicit declaration of function ‘strncasecmp’; did you mean ‘strncmp’? [-Wimplicit-function-declaration]
  195 |   if (!strncasecmp (path, "file://", 7))
      |        ^~~~~~~~~~~
      |        strncmp
msio.c: In function ‘lmp_nanosleep’:
msio.c:822:19: error: storage size of ‘treq’ isn’t known
  822 |   struct timespec treq, trem;
      |                   ^~~~
msio.c:822:25: error: storage size of ‘trem’ isn’t known
  822 |   struct timespec treq, trem;
      |                         ^~~~
msio.c:827:3: warning: implicit declaration of function ‘nanosleep’; did you mean ‘lmp_nanosleep’? [-Wimplicit-function-declaration]
  827 |   nanosleep (&treq, &trem);
      |   ^~~~~~~~~
      |   lmp_nanosleep
make[3]: *** [Makefile:109: msio.o] Error 1